alias cdz="cd $ZDOTDIR"
alias srcz="clear && source $ZDOTDIR/.zshrc"
alias ls="ls --color=auto"
alias l="ls -hAl"
alias gits="git status"
alias gitd="git diff"
alias clip="xclip -r -selection c"
alias nv="nvim"
alias vim="nvim"
alias jc="jack_control"

